### ISSUE TITLE
又搁浅了?

### ISSUE THREAD

**Issue by laputaz** [Smilekris/Gorilla-frontend#2]

**Comment by laputaz** [comment]
??

**Comment by Smilekris** [comment]
??This project isn't under my control

**Comment by laputaz** [comment]
> ??This project isn't under my control

I dont think so.

**Comment by Border-Line** [comment]
start know ?

**Comment by Smilekris** [comment]
??? who is the web developer

**Comment by laputaz** [comment]
No demand and product manager

**Comment by Smilekris** [comment]
dh,you are ,you are the pm.wake up .ok .fight
